# coding: utf-8

"""
    Gitea API

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.23.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import giteapy
from giteapy.models.merge_upstream_request import MergeUpstreamRequest  # noqa: E501
from giteapy.rest import ApiException


class TestMergeUpstreamRequest(unittest.TestCase):
    """MergeUpstreamRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMergeUpstreamRequest(self):
        """Test MergeUpstreamRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = giteapy.models.merge_upstream_request.MergeUpstreamRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
